name: 'Setup'
inputs:
  playwright:
    description: 'Whether or not to install playwright browsers'
    required: false
    default: false
  build-download:
    description: 'Build download artifact name'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install node-gyp-build
      run: bun add --global node-gyp-build

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Install playwright browsers
      if: ${{ inputs.playwright }}
      run: bunx playwright install chromium

    - name: Download build
      if: ${{ inputs.build-download }}
      id: download
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.build-download }}

    - name: Untar build files
      if: ${{ inputs.build-download }}
      run: tar -xvf ${{ inputs.build-download }}.tar
