name: Test 1

on: [push]

permissions:
  issues: write
  pull-requests: write

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1]
    steps:
      - uses: actions/checkout@v3
      - name: Download and install dependencies
        uses: ./.github/actions/setup
      - run: touch report.zip
      - name: Upload report shard
        uses: ./.github/actions/upload-report-shard
        if: always()
