name: Test

on: [push]

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun add --global node-gyp-build

      - run: bun install --frozen-lockfile

      - run: bun run test:coverage

  stateless-parallel:
    name: stateless parallel (${{matrix.shard}})
    runs-on:
      group: default-larger-runners
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun add --global node-gyp-build

      - run: bun install --frozen-lockfile

      - name: Install playwright
        run: bunx playwright install chromium

      - name: Run tests
        run: 'parallel --lb --halt now,success=1,fail=1 ::: \
          "bun run build:glocal && bun run export && bun run wrangle" \
          "bun run e2e:ci"'
        env:
          PLAYWRIGHT_SHARD: ${{ matrix.shard }}
          PLAYWRIGHT_TOTAL: ${{ strategy.job-total }}
          PLAYWRIGHT_PROJECT: stateless-parallel

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: stateless-parallel-report
          path: playwright-report/
          retention-days: 30

  build-stateless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun add --global node-gyp-build

      - run: bun install --frozen-lockfile

      - name: Get contract addresses
        run: 'parallel --lb --halt now,success=1,fail=1 ::: \
          "bun run tenv start -ng -ns -nb" \
          "bun run wait-on ./.env.local"'

      - name: Build stateless and export
        run: bun run build:glocal && bun run export

      - name: Tar stateless files
        run: tar -cvf stateless-build.tar out

      - name: Upload stateless
        uses: actions/upload-artifact@v3
        with:
          name: stateless-build
          path: stateless-build.tar

  build-stateful:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun add --global node-gyp-build

      - run: bun install --frozen-lockfile

      - name: Build stateful and export
        run: bun run build && bun run export

      - name: Tar stateful files
        run: tar -cvf stateful-build.tar out

      - name: Upload stateful
        uses: actions/upload-artifact@v3
        with:
          name: stateful-build
          path: stateful-build.tar

  stateless-serial:
    name: stateless serial (${{matrix.shard}})
    needs: build-stateless
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun add --global node-gyp-build

      - run: bun install --frozen-lockfile

      - name: Download build
        id: download
        uses: actions/download-artifact@v3
        with:
          name: stateless-build

      - name: Untar files
        run: tar -xvf stateless-build.tar

      - name: Install playwright
        run: bunx playwright install chromium

      - name: Run tests
        run: bun run e2e:ci -nb
        env:
          PLAYWRIGHT_SHARD: ${{ matrix.shard }}
          PLAYWRIGHT_TOTAL: ${{ strategy.job-total }}
          PLAYWRIGHT_PROJECT: stateless-serial

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: stateless-serial-report
          path: playwright-report/
          retention-days: 30

  stateful:
    name: stateful (${{matrix.shard}})
    needs: build-stateful
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3]

    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/check-chrome.sh

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun add --global node-gyp-build

      - run: bun install --frozen-lockfile

      - name: Download build
        id: download
        uses: actions/download-artifact@v3
        with:
          name: stateful-build

      - name: Untar files
        run: tar -xvf stateful-build.tar

      - name: Install playwright
        run: bunx playwright install chromium

      - name: Run tests
        run: |
          parallel --lb --halt now,success=1,fail=1 ::: \
          "bun run wrangle" \
          "bun run wait-on http://127.0.0.1:8788 && bunx playwright test --shard=${{matrix.shard}}/${{strategy.job-total}} --project=stateful"
        env:
          SECRET_WORDS: ${{ secrets.SECRET_WORDS }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: stateful-report
          path: playwright-report/
          retention-days: 30
